spring:
  application:
    name: spring-cloud-eureka-server
server:
  port: 8002
eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册到eureka server,默认是true
    fetch-registry: false        #表示是否从eureka server获取注册信息,默认是true
    service-url:
      defaultZone: http://localhost:8002/eureka/   #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
  instance:
    hostname: server-master
